coverage:
  ignore:
    - "internal/adapter/api/api.go" # Ignore this specific file.
    - "internal/config/**"          # Ignore everything under internal/config.
    - "internal/di/**"              # Ignore everything under internal/di.
    - "swagger/**"                  # Ignore everything under swagger.
    - "cmd/**"                      # Ignore everything under cmd.
