// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthcheck": {
            "get": {
                "description": "Checks the health of the application (connection to database)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HealthCheck"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_KauanCarvalho_fiap-sa-product-service_internal_application_dto.HealthCheckOutput"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_KauanCarvalho_fiap-sa-product-service_internal_application_dto.APIErrorsOutput"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_KauanCarvalho_fiap-sa-product-service_internal_application_dto.APIErrorOutput": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_KauanCarvalho_fiap-sa-product-service_internal_application_dto.APIErrorsOutput": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_KauanCarvalho_fiap-sa-product-service_internal_application_dto.APIErrorOutput"
                    }
                }
            }
        },
        "github_com_KauanCarvalho_fiap-sa-product-service_internal_application_dto.HealthCheckOutput": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "fa-sa-product-service",
	BasePath:         "",
	Schemes:          []string{"http"},
	Title:            "Fiap SA Product Service",
	Description:      "Rest API for Fiap SA Product Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
