apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-api-config
data:
  APP_NAME: "fiap-sa-product-service"
  APP_ENV: "production"
  APP_TYPE: "api"
  PORT: "8080"
  DB_PORT: "3306"
  DB_MAX_OPEN_CONNS: "10"
  DB_MAX_IDLE_CONNS: "10"
