apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service-api
  template:
    metadata:
      labels:
        app: product-service-api
    spec:
      containers:
      - name: product-service-api
        image: "${IMAGE_URI}"
        ports:
        - containerPort: 8080
        env:
        - name: APP_TYPE
          value: "api"
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: product-service-config
              key: APP_NAME
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: product-service-config
              key: APP_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: product-service-config
              key: PORT
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: product-service-config
              key: DB_PORT
        - name: DB_MAX_OPEN_CONNS
          valueFrom:
            configMapKeyRef:
              name: product-service-config
              key: DB_MAX_OPEN_CONNS
        - name: DB_MAX_IDLE_CONNS
          valueFrom:
            configMapKeyRef:
              name: product-service-config
              key: DB_MAX_IDLE_CONNS
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: product-service-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: product-service-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: product-service-secrets
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: product-service-secrets
              key: DB_HOST
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 200m
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
