apiVersion: v1
kind: Secret
metadata:
  name: product-service-secrets
type: Opaque
data:
  DB_NAME: "${DB_NAME_B64}"
  DB_USER: "${DB_USER_B64}"
  DB_PASSWORD: "${DB_PASSWORD_B64}"
  DB_HOST: "${DB_HOST_B64}"
